
### Get sleeps
GET http://localhost:3004/sleep


### Create sleep
POST http://localhost:3004/sleep
Content-Type: application/json
{
    "begin": "2024-02-13T21:25:00.000Z",
    "wakeUp": "2024-02-14T06:25:00.000Z",
    "note": "example note..."
}
